### ISSUE TITLE
./lib/dominion/engine/game.rb:68:in `number_available': undefined method `count' for #<Array

### ISSUE THREAD

**Issue by karrde** [jmckible/dominion#1]
%rake server:big_money
  (in /Users/karrde/Sites/jmckible-dominion) 
  ruby -Ilib -rdominion -e 'Server.new(8000).setup.big_money.run'
  Server started on port 8000
  How many players? (2-4)
  2
  Ready to play a 2 game.
  Collecting players 
  Player 1 joined the game
  ./lib/dominion/engine/game.rb:68:in `number_available': undefined method`count' for  #Array:0x86f38 (NoMethodError)
        from ./lib/dominion/engine/player.rb:94:in `select_buy'
        from -e:1:in`each_with_index'
        from ./lib/dominion/engine/player.rb:93:in `each'
        from ./lib/dominion/engine/player.rb:93:in`each_with_index'
        from ./lib/dominion/engine/player.rb:93:in `select_buy'
        from ./lib/dominion/engine/turn.rb:128:in`spend_buys'
        from ./lib/dominion/engine/turn.rb:34:in `play'
        from ./lib/dominion/engine/game.rb:97:in`play'
        from ./lib/dominion/server.rb:33:in `run'
        from -e:1
  rake aborted!
  Command failed with status (1): [ruby -Ilib -rdominion -e 'Server.new(8000)...]

looking at the code:

```
  def number_available(card_type)
    supplies.flatten.count{|card| card.is_a? card_type}
  end
```

I'm not even sure what you're attempting here.  did you want to .each heare, did you want to do an array .length?

**Comment by jmckible** [comment]
Are you on Ruby 1.8.7? I believe Array#count wasn't available until then. I should probably make this degrade better.  It's a habit from Rails.

**Comment by karrde** [comment]
good call:

%ruby -v

ruby 1.8.6 (2008-08-11 patchlevel 287) [universal-darwin9.0]

**Comment by karrde** [comment]
Upgraded and fixed

**Comment by jmckible** [comment]
Since it's fixed for you, I'm not going to make any changes right now. I'm going to focus on finishing implementation of all the Kingdom cards. If this issues comes up again, I'll do a full test against 1.8.6.
